# encoding: utf-8
class Menu(object):
    def config(self,root,**kwargs):
        develop = root.branch(u"Develop", tags="admin")
        develop.packageBranch("System", pkg='sys', tags="admin")
        develop.packageBranch("admin", pkg='adm', tags="admin")
        develop.packageBranch("Glbl", pkg='glbl', tags="admin")
        develop.packageBranch("Test", pkg='test', tags="admin")
        meg_bi = root.branch(u"Meg Bi")
        meg_bi.thpage(u"!!File Importati", table="bi.file")
        meg_bi.thpage(u"!!Anagrafiche", table="bi.anagrafica", viewResource='ViewBase')
        meg_bi.thpage(u"!!Locazioni", table="bi.locazione")
        meg_bi.thpage(u"!!Bonifici", table="bi.bonifico")
        meg_bi.thpage(u"!!F24", table="bi.f24")
        meg_bi.thpage(u"!!PagoPa", table="bi.pagopa")
        config = root.branch(u"Configurazioni", tags="admin")  
        config.thpage(u"!!Tipi file", table="bi.tipo_file")
        config.thpage(u"!!Parametri file", table="bi.parametro_file")
        banche = root.branch(u"Banche")
        banche.thpage(u"!!Istituti", table="bi.banca_istituto")
        banche.thpage(u"!!Filiali", table="bi.banca_filiale")
        servizio = root.branch(u"Servizio", tags="admin")  
        servizio.thpage(u"!!Beni Immobili", table="bi.bene_immobile")
        servizio.thpage(u"!!Beni Mobili", table="bi.bene_mobile")
        servizio.thpage(u"!!Conti Correnti", table="bi.conto_corrente")
        servizio.thpage(u"!!Datori Lavoro", table="bi.datore_lavoro")